### ISSUE TITLE
자동 업데이트 문의?

### ISSUE THREAD

**Issue by mickeyseo** [horyu1234/KakaoTalkNoAdv#2]
대부분의 프로그램에는 업데이트 여부를 자동으로 확인 후, 업데이트 가능하면 자동으로 업데이트를 진행합니다. 이번 광고 제거 프로그램에도 그런 기능이 있나요? 아니면 종종 여기 GitHub에 들어와서 확인해야 하나요?

**Comment by horyu1234** [comment]
현재는 자동 업데이트 기능이 존재하지 않지만, 이후에 프로그램을 이용하시는 분이 늘어날 경우 프로그램 UI 개편, 자동 업데이트 기능 구현 등의 의향이 있습니다.

**Comment by horyu1234** [comment]
@mickeyseo 추가적인 질문이 없는 것으로 보아, 이슈를 닫습니다.
추가적인 질문이 있으시다면 이슈 오픈 또는 새로운 이슈를 생성해주시기 바랍니다.
